function calculateReadingAge (text) {
  let terminalPunctuation = /\.+|\?+|!+/

  let characters = text.split('').filter((char) => /\w/.test(char))
  let words = text.split(' ')
  let sentences = text.split(terminalPunctuation).slice(0, -1)

  return 4.71 * (characters.length / words.length) + 0.5 * (words.length / sentences.length) - 21.43
}

//console.log( calculateReadingAge('Quantum mechanics (QM) is the part of physics that tells us how the things that make up atoms work. QM also tells us how electromagnetic waves like light work. QM is a mathematical framework (rules written in math) for much of modern physics and chemistry. Quantum mechanics helps us make sense of the smallest things in nature like protons, neutrons and electrons. Complex mathematics is used to study subatomic particles and electromagnetic waves because they act in very strange ways. Quantum mechanics is important to physics and chemistry. Quantum is a Latin word that means "how much". So a quantum of energy is a specific amount of energy. Light sources such as candles or lasers shoot out (or "emit") light in bits called photons. Photons are like packets. Each one has a certain little bit of energy.') )

//console.log( calculateReadingAge('Quantum mechanics (QM; also known as quantum physics or quantum theory), including quantum field theory, is a fundamental branch of physics concerned with processes involving, for example, atoms and photons. In such processes, said to be quantized, the action has been observed to be only in integer multiples of the Planck constant. This is utterly inexplicable in classical physics. Quantum mechanics gradually arose from Max Planck\'s solution in 1900 to the black-body radiation problem (reported 1859) and Albert Einstein\'s 1905 paper which offered a quantum-based theory to explain the photoelectric effect (reported 1887). Early quantum theory was profoundly reconceived in the mid-1920s. The reconceived theory is formulated in various specially developed mathematical formalisms. In one of them, a mathematical function, the wave function, provides information about the probability amplitude of position, momentum, and other physical properties of a particle. Important applications of quantum mechanical theory[1] include superconducting magnets, light-emitting diodes and the laser, the transistor and semiconductors such as the microprocessor, medical and research imaging such as magnetic resonance imaging and electron microscopy, and explanations for many biological and physical phenomena.'))